# Generated by Django 5.2.17 on 2026-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Business id e.g. BA-001 (auto-assigned on create).', max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Training', 'Training'), ('Assessed', 'Assessed'), ('Certified', 'Certified'), ('Rejected', 'Rejected'), ('Deployed', 'Deployed')], default='Pending', max_length=20)),
                ('invite_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbassadorComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(blank=True, max_length=200)),
                ('audio_file', models.FileField(blank=True, upload_to='assessment_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('communication_quality', models.FloatField(blank=True, null=True)),
                ('speaking_speed_wpm', models.FloatField(blank=True, null=True)),
                ('filler_rate', models.FloatField(blank=True, null=True)),
                ('nervousness_pct', models.FloatField(blank=True, null=True)),
                ('dominant_mood', models.CharField(blank=True, max_length=40)),
                ('affect_breakdown', models.JSONField(blank=True, default=dict)),
                ('speech_metrics', models.JSONField(blank=True, default=dict)),
                ('linguistic_metrics', models.JSONField(blank=True, default=dict)),
                ('question_relevance', models.JSONField(blank=True, default=dict)),
                ('video_relevance', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=40)),
                ('question_type', models.CharField(default='verbal', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('consent', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict, help_text='Map of question id (str) -> selected answer text')),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_threshold', models.PositiveSmallIntegerField(default=75, help_text='Minimum communication_quality score (0–100) required to certify a BA.')),
                ('a_plus_threshold', models.PositiveSmallIntegerField(default=90, help_text='Optional higher band for A+ labelling (display / future use).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date of the shift')),
                ('day_key', models.CharField(help_text='Mon…Sun for UI week board', max_length=3)),
                ('shift_label', models.CharField(max_length=64)),
                ('peak_recommended', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Scheduled', 'Scheduled'), ('Conflict', 'Conflict')], default='Open', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_lat', models.FloatField(blank=True, null=True)),
                ('check_in_lng', models.FloatField(blank=True, null=True)),
                ('check_in_accuracy_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'shift_label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Business id e.g. ST-001 (auto-assigned on create).', max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('footfall', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('peak_hours', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('PARTIAL', 'Partial'), ('Pending', 'Pending'), ('INACTIVE', 'Inactive')], default='Pending', max_length=20)),
                ('coverage', models.PositiveSmallIntegerField(default=0)),
                ('bas', models.PositiveSmallIntegerField(default=0)),
                ('today_footfall', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('qr_slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='store_qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Wheel / prize label', max_length=120)),
                ('win_amount', models.CharField(help_text='e.g. Rs. 100 OFF', max_length=80)),
                ('win_detail', models.CharField(blank=True, max_length=200)),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reward is shown when the shopper wins / claims')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=300)),
                ('options', models.JSONField(default=list, help_text='List of answer choice strings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='training_videos/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField(blank=True)),
                ('questions_json', models.JSONField(blank=True, default=list, help_text='HO-authored assessment questions: [{id, type, question, description}, …]')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
