# Generated by Django 5.2.17 on 2026-09-28 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ambassadors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.ambassador'),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.ambassador'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.assessmentsession'),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.assessmentsession'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='api.ambassador'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.store'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='api.store'),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_complaints', to='api.store'),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassadors', to='api.store'),
        ),
        migrations.AddField(
            model_name='storereward',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.store'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Leave empty only for legacy fallback questions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='api.store'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('session', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentanswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(fields=('store', 'order'), name='unique_survey_question_order_per_store'),
        ),
    ]
