# Generated by Django 5.2.14 on 2026-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_survey_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='ho_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer Complaint'), ('ba', 'BA Complaint'), ('insights', 'Insights')], db_index=True, default='ba', max_length=20),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ambassadorcomplaint',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ambassadorcomplaint',
            name='complaint',
            field=models.TextField(help_text='Full details / complaint body.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='ambassadorcomplaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], db_index=True, default='Open', max_length=20),
        ),
    ]
