# Generated by Django 5.2.17 on 2026-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expand_ambassador_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='early_leave_reason',
            field=models.TextField(blank=True, default='', help_text='Filled when BA checks out before shift end time.'),
        ),
    ]
