# Generated by Django 5.2.17 on 2026-09-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_early_leave_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('stock_json', models.JSONField(blank=True, default=dict)),
                ('sales_json', models.JSONField(blank=True, default=dict)),
                ('other_brands_json', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('excel', 'Excel upload'), ('manual', 'Manual forms')], default='manual', max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='api.ambassador')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='api.shiftassignment')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ba_daily_reports', to='api.store')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['ambassador', '-date'], name='api_badaily_ambassa_357710_idx')],
            },
        ),
    ]
