# Generated by Django 5.2.17 on 2026-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ba_supervisor_package_kpis'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batarget',
            new_name='api_batarge_ambassa_df335b_idx',
            old_name='api_batarge_ambassa_idx',
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(db_index=True, help_text='Business store code (required). Duplicates get -1, -2, …', max_length=32, unique=True),
        ),
    ]
