# Generated by Django 5.2.14 on 2026-09-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_supervisor_login_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaAttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('day_key', models.CharField(blank=True, default='', max_length=3)),
                ('shift_label', models.CharField(blank=True, default='', max_length=64)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('early_leave_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='api.ambassador')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='api.shiftassignment')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ba_attendance_days', to='api.store')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('ambassador', 'date'), name='uniq_ba_attendance_day')],
            },
        ),
    ]
