# Generated by Django 5.2.14 on 2026-09-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ba_attendance_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='batarget',
            name='assigned_skus',
            field=models.JSONField(blank=True, default=list, help_text='Pack SKUs assigned under this target row (category or multi-SKU upload).'),
        ),
    ]
